### ISSUE TITLE
Blockstörung simulieren

### ISSUE THREAD

**Issue by stblassitude** [vvmev/lst-tasks#118]
Art der Störung:
* Unterbrechung der Streckenblockleitung: A->B, B->A, Erl A<->D
* Unterbrechung der Bahnhofsblockleitung: Befehl P4, Fahrstraßenauflösung a

Umsetzung: Unterbrechung der Leitung X durch einen Schalter.

Vorbereitung:
* 2-Draht- oder 4-Drahtschaltung?
* Leitungen zwischen A-Dorf und B-Heim identifizieren
* Freie Leitungen zum Lokführerpult identifizieren (2 pro Blockverbindungsleitung)
* Freie Schalter im Lokführerpult in A-Dorf nutzen

**Comment by dl8xas** [comment]
Implementiert, Kippschalter um Blockstörungen zu aktivieren wurden in das Trainerpult eingebaut. Schalter sind beschriftet, Dokumentation vor Ort.
